version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:13.8.0  
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm test
    
  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"        

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test


    